from tkinter import *
from tkinter import ttk
root = Tk()
root.title("Student Record Activation")
Name_label = Label(root, text = "Name").grid(row=0,column=0)
Name_entry = Entry(root,width=30).grid(row=0,column=1)
Major_label = Label(root, text = "Major").grid(row=1,column=0)
Major_entry = Entry(root,width=30).grid(row=1,column=1)
Sex_label = Label(root, text = "Sex").grid(row=2,column=0)
Sex_entry = Entry(root,width=30).grid(row=2,column=1)
Gpa_label = Label(root, text = "GPA").grid(row=3,column=0)
Gpa_entry = Entry(root,width=30).grid(row=3,column=1)
ID_label = Label(root, text = "ID").grid(row=0,column=2)
ID_entry = Entry(root,width=30).grid(row=0,column=3)
Age_label = Label(root, text = "Age").grid(row=1,column=2)
Age_entry = Entry(root,width=30).grid(row=1,column=3)
Address_label = Label(root, text = "Address").grid(row=2,column=2)
Address_entry = Entry(root,width=30).grid(row=2,column=3)
btn = ttk.Button(root ,text="View").grid(row=4,column=3)
btn1 = ttk.Button(root ,text="Search Entry").grid(row=5,column=3)
btn2 = ttk.Button(root ,text="Add Entry").grid(row=6,column=3)
btn3 = ttk.Button(root ,text="Update selected").grid(row=7,column=3)
btn4 = ttk.Button(root ,text="Delete selected").grid(row=8,column=3)
btn5 = ttk.Button(root ,text="Clear").grid(row=9,column=3)
scrollbar = Scrollbar(root)
scrollbar.grid(row=4,column=0)
mylist = Listbox(root, yscrollcommand = scrollbar.set )
root.mainloop()